### ISSUE TITLE
Flatten the Folder Structure

### ISSUE THREAD

**Issue by tburgin** [grahamgilbert/crypt#10]
-  Crypt/ - Contains Plugin Classes. Contains Folders for Mechs and Views.
-  Crypt.xcodeproj
-  LICENSE
-  Package/ - Contains all the supporting scripts and plists for building a package.
-  README

**Comment by grahamgilbert** [comment]
Am I being blind in not seeing a pull request for this?

**Comment by tburgin** [comment]
No pull yet. Still working!

**Comment by tburgin** [comment]
Merged https://github.com/grahamgilbert/crypt2/commit/05ee16ef52df3484d79083ec1d0cb3040ec4fa85
