### ISSUE TITLE
Privileged authorization mechanisms unstable on Big Sur. 

### ISSUE THREAD

**Issue by weswhet** [grahamgilbert/crypt#103]
As of Betas 3 and 4 of macOS Big Sur, crypt is unstable and should not be used. We are currently experiencing issues with using privileged authorization mechanisms at login and have filed Feedbacks accordingly.

Please follow the steps in the Wiki for troubleshooting logins if you have a Beta3,4 machine that is not able to log in.

**Comment by weswhet** [comment]
Per the B6 release notes

```
(Beta 6) User login at the Login Window now completes when using certain types of Authorization plugins.
```

Please try crypt v4 on Big Sur Beta 6 and report back.

**Comment by weswhet** [comment]
Appears to be stable in B6-B8

**Comment by arubdesu** [comment]
I believe this can get closed out?
