### ISSUE TITLE
FYI regarding Rosetta-translated SecAuthPlugin causing looping failures on later Big Sur releases

### ISSUE THREAD

**Issue by arubdesu** [grahamgilbert/crypt#108]
This is just a heads-up that if you're like me and have a lot of Apple Silicon devices running the 4.0.0 release of Crypt, Apple has a probable bug with (intermittently dropping rosetta2 during OS upgrades, and) a stage during the process where it can "silently" log the user in during one of its reboots before "first login optimization", since softwareupdate prompts/stores the users password before reboot. We assume rosetta still being intact and rejecting Crypt when translated is causing the auto-login to fail, on the second visible 'loop' it even adds the "Other" login option alongside the primary user. We started noticing error reports as if passwords were failing, but nothing user-related was able to fix it from ~11.4 on. We don't have authoritative numbers of upgrade attempts vs. failures, but we do not rosetta has reinstalled on ~1/3rd of the fleet.

A fix we came up with after help from a certain prince was to boot into recovery, have the end user auth and mount the internal disk, then rm the path to auth.db (assuming the internal drive name wasn't renamed and this symlink works)
```sh
/bin/rm /Volumes/Data/private/var/db/auth.db
```
Additionally we did the "paranoia/voodoo" thing of running Disk Utility -> First Aid while still in recovery, since it finishes in seconds and we still had failures without running it.

I have started the rollout of an arm-specific build with no other code changes (except a few auto-fixed suggestions by xcode) as version 4.0.1, I'll update as we get this into prod to the point that new enrolls only use this version. I assume this will be the fix we need to get existing devices upgraded, but I'm working with Apple on confirming this arm version will avoid the error.

**Comment by grahamgilbert** [comment]
4.1 is a universal build - please test and let me know.

**Comment by tristanthomas** [comment]
I deployed the universal build, Crypt v4.1.227 to my Apple Silicon device (macOS 11.6 without Rosetta 2 installed) and confirmed that the login loop issue is no longer reproducible.
