### ISSUE TITLE
Crypt postinstall should not use the symbolic link

### ISSUE THREAD

**Issue by erikng** [grahamgilbert/crypt#112]
I noticed a weird error on one of my machines where the python symlink was pointing to `3.8`

`python -> /Library/Crypt/Python.framework/Versions/3.8/bin/python3`

The path was actually `/Library/Crypt/Python.framework/Versions/3.9/bin/python3`. This broke the `checkin` script but also broke the postinstall. It looks like some machines have `/Library/Crypt/Python.framework/Versions/Current/bin/python3` which should be stable, but I think it might make sense to not point to the symlink in case it's broken. I'm now worried that fleets are broken and don't even know they are.

**Comment by aysiu** [comment]
I think this is fixed now. I took a look at the 4.0 package, and the symlink goes to 3.8:
```
python -> /Library/Crypt/Python.framework/Versions/3.8/bin/python3
```
But when I looked at the 4.1 package, the symlink goes to the current version:
```
python -> /Library/Crypt/Python.framework/Versions/Current/bin/python3
```
https://github.com/grahamgilbert/crypt/blob/master/Package/Makefile#L41

But ultimately, it sounds as if you're saying it shouldn't use a symbolic link at all?

**Comment by erikng** [comment]
Whatever happened on my machine leads me to believe that the symbolic link failed to be updated from the pkg to pkg install. We've been on 4.1 for a very long time and I missed this for potentially years. 

But yes in order to ensure nothing ever goes wrong with the symlink I question whether we should even use it.

it provides such little value especially if we use the symlink provides in the relocatable python to begin with. It's a symlink to another symlink

**Comment by weswhet** [comment]
Hopefully we can just do away with python all together in favor of swift. #114
