### ISSUE TITLE
Migrate Python Code to Swift.

### ISSUE THREAD

**Issue by weswhet** [grahamgilbert/crypt#114]
I believe it's time we finally migrate all the python code which is the post install script in the package and then checkin code over to Swift.

I've already got the post install script written just need to work on the checkin code. This should simplify the project greatly.

**Comment by erikng** [comment]
You want the post install in swift? As a compiled binary?

**Comment by wesw-stripe** [comment]
How I currently have it is swift code that gets compiled during the pkg build phase.

Could also have it in the Resources directory of the plugin and have 2 lines of bash call it for the post install.

**Comment by weswhet** [comment]
How I currently have it is swift code that gets compiled during the pkg build phase.

Could also have it in the Resources directory of the plugin and have 2 lines of bash call it for the post install.
