### ISSUE TITLE
AuthPlugin Fails on 10.12.

### ISSUE THREAD

**Issue by weswhet** [grahamgilbert/crypt#18]
Initial Tracking for macOS Sierra (10.12) issues.  

Login on a decrypted volume yields no prompt to restart. On the next logout though you get the “To set up FileVault with this user, enter the password for {user}" prompt. Entering the password here successfully enables filevault.

**Comment by grahamgilbert** [comment]
Output of fdesetup status?

Sent from my iPhone

On Tue, Jun 14, 2016 at 7:02 PM +0100, "Wesley Whetstone" notifications@github.com wrote:

Initial Tracking for macOS Sierra (10.12) issues.  

Login on a decrypted volume yields no prompt to restart. On the next logout though you get the “To set up FileVault with this user, enter the password for {user}" prompt. Entering the password here successfully enables filevault.

**Comment by weswhet** [comment]
`FileVault is Off, but needs to be restarted to finish.
Deferred enablement appears to be active for user 'wes'`

**Comment by weswhet** [comment]
After further investigation a clean install of the crypt pkg fixes it. During the upgrade it appears the authdb is cleared.

**Comment by grahamgilbert** [comment]
Odd. If we can confirm, I'd say this is a bug to be reported to the fruit conpany. The auth dB should persist upgrades. 

Sent from my iPhone

On Tue, Jun 14, 2016 at 9:21 PM +0100, "Wesley Whetstone" notifications@github.com wrote:

After further investigation a clean install of the crypt pkg fixes it. During the upgrade it appears the authdb is cleared.

**Comment by weswhet** [comment]
definitely confirmed by multiple parties. I attempted a bug report but the bug report feature isn't working ATM 😨

**Comment by weswhet** [comment]
Bug Filed with said fruit company.

**Comment by grahamgilbert** [comment]
Same here. Please remember to mention the number of impacted devices in your report. If you have AppleSeed, even better.

**Comment by grahamgilbert** [comment]
Righty-o, since this isn't an issue with Crypt, rather than 10.12, I'm closing this one
