### ISSUE TITLE
Add preference/logic to only submit within corporate network.

### ISSUE THREAD

**Issue by erikng** [grahamgilbert/crypt#21]
Leaving this here so I don't forget, but it would be great if crypt2 could detect the machine is on the corporate network and if it detects it isn't, skip submitting data).

While the submission will currently fail, there could be a potential flaw down the line (SSL vuln, DNS vuln, or within the plugin itself) where someone could potentially retrieve keys from machines. Removing the entire submission would mitigate this entirely.

Corporate network detection is somewhat of an esoteric concept, so I'm sure further discussion will be needed.

**Comment by grahamgilbert** [comment]
Hmm, I have submissions allowed from anywhere and restrict everything else to corp via nginx. I don't see any reason to restrict this unless I'm missing something?

**Comment by erikng** [comment]
But that restriction is for crypt server right?

**Comment by erikng** [comment]
To be clearer, this option would be to prevent any data from being passed unless on a priveleged network.

**Comment by grahamgilbert** [comment]
Ok. I don't need this at the moment. Pull requests accepted etc

**Comment by grahamgilbert** [comment]
I would actually say the best way around this would to be to not use the built in launch daemon, then kick off the checkin with crankd. You could then implement whatever checks you need to determine if you're on the right network.

**Comment by erikng** [comment]
Okay I'll have to play with crankd.

Sent from my iPhone

On Aug 3, 2016, at 4:48 AM, Graham Gilbert <notifications@github.com<mailto:notifications@github.com>> wrote:

I would actually say the best way around this would to be to not use the built in launch daemon, then kick off the checkin with crankd. You could then implement whatever checks you need to determine if you're on the right network.

##
