### ISSUE TITLE
Crypt Prompt after logout 10.10

### ISSUE THREAD

**Issue by jurczykmaf** [grahamgilbert/Crypt#22]
Hey Graham, 

                        We are beginning to upgrade Macbook Pro's to 10.10, when we logout to encrypt our laptops the usual crypt screen does not pop up as it usually did on 10.8 and 10.9. Am i missing something?

**Comment by grahamgilbert** [comment]
I'm afraid I don't follow. Crypt doesn't show anywhere by default. If you have it configured to run via a loginhook, it will run at login, not logout. More info needed, I'm afraid!

**Comment by jurczykmaf** [comment]
Thanks for the quick response Graham! So i have crypt to set up to begin the encryption process at logout. I'm installing the crypt client and my crypt config via Munki. This set up works if i have osx 10.8 on a laptop. So instead of 10.8 i basically switched my image to 10.10. I log in fine, i can see crypt in /usr/bin/ and i can see its pointing to my crypt server. At logout i get a black screen where i would normally get the crypt credentials screen. It seems like that crypt credentials screen does not come to the forefront. Have you seen this before? Do you think the loginhook is the way to get around this?

**Comment by grahamgilbert** [comment]
I've never tried Crypt with a logout hook - our use case is that the machine needs to be encrypted prior to the user accessing the machine. It definitely works with a login hook, so if that's an acceptable solution to you, I'd run with that.
