### ISSUE TITLE
No server certificate verification due to use of urllib2

### ISSUE THREAD

**Issue by keeleysam** [grahamgilbert/Crypt#23]
Crypt client currently uses urllib2 to talk to the server.  As urllib2 does not support SSL certificate verification, it is susceptible to attacks which can intercept the key.

**Comment by grahamgilbert** [comment]
Well this is embarrassing. I changed it to curl on my copy but didn't commit it as I had the intention of moving it over to gurl. That never happened, so I'll package up what I have a commit it.

**Comment by grahamgilbert** [comment]
Fixed in https://github.com/grahamgilbert/Crypt/commit/d4a2f8fe10bac1c6d2a518d46b6aa8f473372d42
