### ISSUE TITLE
If RemovePlist is set to True, loss of functionality

### ISSUE THREAD

**Issue by erikng** [grahamgilbert/crypt#25]
When testing the master branch, if `RemovePlist` is set to True and a key is escrowed, Crypt loses the most of the new functionality:

https://github.com/grahamgilbert/crypt2/blob/master/Package/checkin#L61
https://github.com/grahamgilbert/crypt2/blob/master/Package/checkin#L97
https://github.com/grahamgilbert/crypt2/blob/master/Package/checkin#L130
https://github.com/grahamgilbert/crypt2/blob/master/Package/checkin#L146
https://github.com/grahamgilbert/crypt2/blob/master/Package/checkin#L163
https://github.com/grahamgilbert/crypt2/blob/master/Package/checkin#L184-L193

Perhaps this should be set to `RemoveKey` vs `RemovePlist`. This would require the least amount of code changes, however it is a breaking change due to the administrative burden.

**Comment by grahamgilbert** [comment]
These line numbers don't really make sense now, so I don't really know what is being referred to here.

**Comment by erikng** [comment]
I don't even remember anymore. Let's close for now.
