### ISSUE TITLE
Add Disabled Preference Key

### ISSUE THREAD

**Issue by erikng** [grahamgilbert/crypt#26]
Instead of leaving the URL undefined, it would be great if a `Disabled` key could be added. This would allow me to dynamically turn off Crypt2 via my own Chef runs (and still have the client, URL defined if I later need to turn it on).

**Comment by grahamgilbert** [comment]
What benefit do we get over removing the server url pref or removing it from the mechs list in the auth db? Both of these are just as easy as setting another pref with your config management tool, no?

**Comment by erikng** [comment]
Fair point, but it just seems like a safer option. The postinstall will re-enable the list in the authdb and I don't want to run into some kind of race condition where we upgrade and it enables itself on a machine that shouldn't have it.

Using another key would ensure that doesn't happen.

**Comment by grahamgilbert** [comment]
But what about removing the server url key? The installer doesn't touch that.

**Comment by erikng** [comment]
Okay I'll play around with my internal overrides. It probably is the easier as far as code goes. Don't close yet? (please).

**Comment by grahamgilbert** [comment]
Basically I don't need this. If you want to put in a PR to add it, I'll merge it.

**Comment by erikng** [comment]
I've figured out an appropriate chef fix for this. I'll close for now unless someone else wants this.
