### ISSUE TITLE
Key rotation and server availability check.

### ISSUE THREAD

**Issue by dimaui** [grahamgilbert/crypt#33]
Hi,

i was wondering if there are any plans on adding a key rotation setting to the application?
Another cool feature would be for the app to check if it can reach the server before it rotates the key so that the key on the machine always matches the one on the server.
Thanks for a great tool!

**Comment by grahamgilbert** [comment]
Yes, there has been discussion on the topic on macadmins slack. It's a more complex topic to solve than it first seems.

**Comment by grahamgilbert** [comment]
Closing this in favor of #43 as this is two issues in one.
