### ISSUE TITLE
Minor - Misleading dialog during postpone

### ISSUE THREAD

**Issue by arubdesu** [grahamgilbert/crypt#36]
I tested postponement with the latest release, and it shows the older 'going to restart now' notice but then allows login. It would make folks nervous if they really are certain they NEED postponement, and I'm sure it's the first thing my testers would say. Haven't tested various hardware models/OSes, but this occurred on fully patched 10.12.4.

**Comment by grahamgilbert** [comment]
Ok, so what would you propose instead?

**Comment by arubdesu** [comment]
This behavior no longer appears with build 2.2.0.63 I got from @weswhet, seems to offer no postponement anymore. Closing for the time being.
