### ISSUE TITLE
Swift 3

### ISSUE THREAD

**Issue by chinh-tran** [grahamgilbert/crypt#37]
Hi, are you planning to update the project to Swift 3?

**Comment by grahamgilbert** [comment]
Are you volunteering?

In all seriousness, I see no advantage. Especially when we don't even know if FileVault in it's current form will even exist with APFS. If someone want's to do it, I'll accept the PR.

**Comment by tburgin** [comment]
I believe I did most of the leg work for swift3 migration here. Mainly because I was curious.
https://github.com/tburgin/crypt2
Though I don't use crypt anymore and have not tested my fork. Anyone who wants to finish this off feel free.

**Comment by weswhet** [comment]
@tburgin I was testing your fork and noticed it doesn't seem to capture the output from the `fdesetup enable` command properly so it fails to write the recovery key to disk. I tried to fix it but my swift skills fell short. If you get a chance to take a look, cool. If not I get it as my thoughts are similar to grahams for APFS.

**Comment by tburgin** [comment]
@weswhet Ah, yeah I forgot you mentioned that. I will take a look and update the fork.

**Comment by weswhet** [comment]
https://github.com/grahamgilbert/crypt2/pull/42 address this.

**Comment by tburgin** [comment]
Yippee!
