### ISSUE TITLE
Key validation

### ISSUE THREAD

**Issue by grahamgilbert** [grahamgilbert/crypt#44]
We need an option to validate the keys on every run if:

* The machine is on 10.12.5 and up
* The preference to store the key on disk is also set
* The preference to rotate used keys is set

If the key fails to unlock the disk, we should remove the config plist, which would force the auth plugin to regenerate a new one during next login.

**Comment by grahamgilbert** [comment]
Addressed in #45

**Comment by weswhet** [comment]
Closable?
