### ISSUE TITLE
On 10.13 Crypt does not write the key to disk

### ISSUE THREAD

**Issue by mikedodge04** [grahamgilbert/crypt#56]
On 10.13 Crypt successfully encrypts but does not write the key to disk with a custom location.

**Comment by weswhet** [comment]
Can you provide the version you are using, as well as logs using `sudo /usr/bin/log show --predicate '(subsystem == "com.grahamgilbert.crypt")' --style syslog --debug --info --last 24h`

**Comment by weswhet** [comment]
Closing this as I can't reproduce.
