### ISSUE TITLE
Remove restart from pkg

### ISSUE THREAD

**Issue by clburlison** [grahamgilbert/crypt#64]
PR https://github.com/grahamgilbert/crypt/pull/63 might have been merged a bit early in its current form into the `dev` branch. 

The above change will remove the restart requirement with the package. Mactroll brought up a good point that Fast User Sessions (FUS) might be an issue in its current form. I planned on testing this but ran out of time for this week and my VM stopped working properly.

We should validate that issues do occur when we use the `killall` option that is currently implemented. If issues do occur we should try `kill -1 ProcID` or `kill -9 ProcID`. The code is already setup for this testing we just need to do the testing.

**Comment by weswhet** [comment]
Closing as PR has been merged.
