### ISSUE TITLE
changerecovery can not be used on APFS

### ISSUE THREAD

**Issue by bochoven** [grahamgilbert/crypt#65]
From the manpage of fdesetup

``` 
changerecovery -personal | -institutional -user [[-keychain] | [-certificate path_to_cer_file]] [-key path_to_keychain_file]
                [-inputplist] [-verbose]
                Adds or updates the current recovery key.   Either personal and/or institutional options must be specified.  When changing
                the personal recovery key, the updated personal recovery key will be automatically generated.   When changing either key, the
                old value will be removed and replaced.  Because APFS volumes require an OD authentication before it will allow for the
                change, the current recovery key cannot be used for the authentication.  On CoreStorage volunes the -key option can be used
                to unlock FileVault.   More information on this is described elsewhere in this document.```

**Comment by bochoven** [comment]
Same goes for ```# /usr/bin/fdesetup usingrecoverykey
This command is not supported on APFS volumes.```

**Comment by grahamgilbert** [comment]
This is why we delete the local recovery key and regenerate it on next login if the validation fails. 

https://github.com/grahamgilbert/crypt/blob/master/Package/checkin#L200

I guess I’m missing something here?

**Comment by bochoven** [comment]
I'm referring to https://github.com/grahamgilbert/crypt/blob/master/Package/checkin#L144-L154 and https://github.com/grahamgilbert/crypt/blob/master/Package/checkin#L227-L245 which return errors when called on an APFS system

**Comment by weswhet** [comment]
That code was left in hopes that Apple would bring the ability back / fix it.

**Comment by bochoven** [comment]
Ok, was calling `checkin` manually for testing purposes and saw these functions erroring. If that’s by design, I’m closing this.
