### ISSUE TITLE
Local Recovery key removed after software updates.

### ISSUE THREAD

**Issue by weswhet** [grahamgilbert/crypt#68]
I've noticed on several machines that after applying a dot release update the checkin script will remove the local key `2018-01-23 12:47:12 PM - INFO: Stored recovery key is not valid, removing from disk`. I feel it is getting a false positive. No actual evidence yet just posting for transparency.

**Comment by clburlison** [comment]
I've also seen this on my fleet as well. An untested idea, maybe we can test for the `com.apple.Dock` process in the `rotate_invalid_key()` function right after the OS checks? Right now this seems like something weird is happening with `fdesetup validaterecovery` being ran before it has the right context.

https://github.com/grahamgilbert/crypt/blob/d1ad3ebb82a17fcd57bd6570bff6d56f70aa0789/Package/checkin#L174-L206

**Comment by grahamgilbert** [comment]
I guess that sounds reasonable

**Comment by weswhet** [comment]
I wrote something locally to see if a user is logged in, skips validation if no one is. Waiting for a test machine to upgrade to see if that helps.

**Comment by weswhet** [comment]
^ that fixed it, I’ll have a PR after lunch.

**Comment by weswhet** [comment]
resolved in #69
