### ISSUE TITLE
v.3.3.1 does not install at loginwindow

### ISSUE THREAD

**Issue by andrewvalentine** [grahamgilbert/crypt#73]
Installation of Crypt 3.3.1 via Munki fails if the machine is at the loginwindow. This has been tested on a 10.12.6 VM and a 10.13.3 MacBook Air.

If installation starts at the loginwindow (for example, as part of a Munki bootstrap workflow), the MSC GUI is displayed as normal. After installation begins, there is a brief flash of black, and the MSC run restarts. The MSC GUI displays "Starting...", while `ManagedSoftwareUpdate.log` loops with the message `Another instance of managedsoftwareupdate is running as pid...`. Clicking "Stop" has no effect.

I've successfully tested installing Crypt v.3.1.0 at the loginwindow.

**Comment by bryanheinz** [comment]
I was able to replicate this on a 10.12.6 MBA. Worked fine when installing in the GUI, but got the black screen flash when installing at the loginwindow. I logged back into the machine and ran managedsoftwareupdate to see the `Another instance of managedsoftwareupdate is running` message. v3.1.0 worked fine for me on the loginwindow as well.

**Comment by weswhet** [comment]
@andrewvalentine I'm assuming you mean you're having trouble with v3.1.1, not 3.3.1, as that version doesn't exist.

**Comment by andrewvalentine** [comment]
@weswhet Ha...yes. Apologies. Numbers are hard.

**Comment by weswhet** [comment]
Fixed by #74. New release should be out soon. Please re-open if not fixed.
