### ISSUE TITLE
log rotation

### ISSUE THREAD

**Issue by erikng** [grahamgilbert/crypt#78]
We should probably add a log rotation for crypt.

Questions to probably be answered:

- Should we move log location or make that a preference?
- What is the threshold (in size) for log rotation?

**Comment by clburlison** [comment]
My opinions

> Should we move log location or make that a preference?

No. Sane defaults and "Keep it simple, stupid".

> What is the threshold (in size) for log rotation?

5 MB

That file size gives plenty of data. For companies that want to store these logs for longer amounts of time, they should ship off box into a Splunk/ES/Logstash/etc.

The following should do the trick:
https://stackoverflow.com/a/24505345

**Comment by weswhet** [comment]
@erikng @clburlison we use a newsyslog config for this.
`/etc/newsyslog.d/crypt.conf`
```
# logfilename             [owner:group]       mode   count size(KiB) when   flags [/pid_file] # [sig_num]
/var/log/crypt.log        root:wheel          644    3     2560      *      JN
```

**Comment by grahamgilbert** [comment]
I don’t object to putting this in the default package.

**Comment by weswhet** [comment]
cool, I'll add it.

**Comment by clburlison** [comment]
two years later 👀 
didn't even know this issue still existed but sounds good to me as well
