### ISSUE TITLE
Integrate with FV2AuthPlugin

### ISSUE THREAD

**Issue by tburgin** [grahamgilbert/crypt#8]
-  Add a XPC Service for FV2 user additions
  -  Can run as non-priv.
  -  Uses undocumented functions from dylibs. The use of a XPC Service will move the use of these undocumented functions into their own process. If Apple changes / breaks these functions in the future, it will not break the login window.
-  Integrate with the user exclusions options.
-  Add options to enable or disable user additions.

**Comment by grahamgilbert** [comment]
Is this still on the cards @tburgin after your job move?

**Comment by tburgin** [comment]
It is! Just have to find time!

**Comment by grahamgilbert** [comment]
:+1: Will keep this open then.
