### ISSUE TITLE
Issue with 10.14 and Crypt

### ISSUE THREAD

**Issue by jeff1649** [grahamgilbert/crypt#92]
Hello,

I am new to Crypt and we have just done an upgrade of a Mac from 10.12 to 10.14 to test.  One issue I have run into, is after the upgrade, the machines sit at a loading screen upon restart for a very long time (45min to sometimes hours and even in safe mode).

I initially removed all products I could off the machine to verify what might be impacting this.  Upon building a new machine with 10.14, I had just installed Crypt and once it prompted for the login (initial crypt login) It would then go to the loading screen where it would take forever to get into the machine.

What might be the best way to remove Crypt from the machine?  Is Crypt 2 what i should be using for 10.14?

Has anyone by chance seen this same behavior?  

Any help is most appreciated.

Thanks in advance,

jeff

**Comment by weswhet** [comment]
@jeff1649 Which version exactly of crypt are you using?

**Comment by grahamgilbert** [comment]
Crypt 3.3.0 is the current release. Crypt 2 was released 18 months ago.

**Comment by jeff1649** [comment]
@weswhet What is the best way to find that info?

**Comment by weswhet** [comment]
finder show should the version for /Library/Security/SecurityAgentPlugins/Crypt.bundle

**Comment by weswhet** [comment]
also look at what version you are deploying.

**Comment by jeff1649** [comment]
Sorry for the delay in response.  

I am not seeing the file in the location provided (even after showing all files).  By looking in Munki Admin, it looks like the Crypt agent is very old.  Version 0.6.  There is also a CryptLoginHook, version 1.0.

Where can I find the current release of 3.3.0?

**Comment by grahamgilbert** [comment]
https://github.com/grahamgilbert/crypt/releases

Closing this as crypt 0.6 has been deprecated for several years and definitely untested since at least 10.10ish. 

Please drop by #crypt on MacAdmins.org slack if you have issues upgrading.
