### ISSUE TITLE
Sort by date sorts dates as alphabetical String

### ISSUE THREAD

**Issue by ghost** [grahamgilbert/crypt#94]
When sorting by Date stored, returns the dates sorted alphabetical, as in April is first, September is last.

**Comment by weswhet** [comment]
This should have been fixed in https://github.com/grahamgilbert/Crypt-Server/pull/56

**Comment by weswhet** [comment]
Closing this as it is Crypt-Server, not the client. Please open a new one on Server project if you can verify that this is happening on 3.0
