### ISSUE TITLE
Automatically add users not working 

### ISSUE THREAD

**Issue by adambarnett52** [grahamgilbert/crypt#95]
On OSX 10.13 usig the current master release of Crypt i have set the following 
```
$ sudo defaults write /Library/Preferences/com.grahamgilbert.crypt FDEAddUser -bool TRUE
```
But the user does not get added to the list of users able to unlock the disk. I still need to go into system prefs -> Security -> FileVault -> Enable Users 

Thanks
Adam

**Comment by grahamgilbert** [comment]
This was removed as it relies on a bug in CoreStorage so only worked on HFS+ volumes. This bug was fixed with the move to APFS.

**Comment by adambarnett52** [comment]
Thanks
